[package]
name = "axum-example"
version = "0.3.0"
edition = "2021"

[dependencies]
cloudevents-sdk = { version = "0.7.0", features = ["axum-lib", "axum", "async-trait"] }
axum = "^0.8.0-rc.1"
axum-extra = { version = "0.10.0-rc.1", features = ["protobuf"] }
http = "^1.2"
tokio = { version = "^1", features = ["full"] }
tracing = "^0.1"
tracing-subscriber = "^0.3"
tower-http = { version = "0.6.2", features = ["trace"] }
google-cloudevents = "^0.1.3"